### ISSUE TITLE
Add `isSome`, `isNone`, `isErr`, and `isOk`

### ISSUE THREAD

**Issue by mleonhard** [nlfiedler/oxidized#12]
I'm writing some slightly complicated networking error handling code.  `Result.when` takes a closure which cannot cause the outer function to return early.  This limits its usefulness.  I need `Result.isOk` and `Option.isSome`.

**Comment by nlfiedler** [comment]
Right, they were added back in commit bb252be, but not yet released.

**Comment by nlfiedler** [comment]
And now this has been released in 4.2.0 on pub.dev and here as "v4.2.0". Hope that helps.
