### ISSUE TITLE
Feature Request: Additional Methods for Result Handling

### ISSUE THREAD

**Issue by amaxcz** [nlfiedler/oxidized#26]
I hope this message finds you well. :)

I am writing to request the addition of some convenient methods for handling Result types in your library. As a novice Rust developer, I appreciate the simplicity and expressiveness of the Result type and its associated methods in Rust, and I would like to see similar functionality in your Dart library.

I have taken the liberty of implementing these methods as extensions to the Result and Future<Result> classes. These methods allow for easier and more concise handling of Ok and Err values without the need for exceptions.

I have been working with Rust's Result type, which provides a convenient ? operator for unwrapping values and allowing one-liner expressions. I noticed that your library provides similar functionality through the matchOk and matchErr methods (and unwrapOrNull). I must say that these methods have greatly improved my productivity when dealing with Result types in Dart.

I wanted to request a small addition to your library. I would love to see an operator similar to Rust's ? that allows for concise one-liner expressions when handling Result types. For example, it would be great to have the ability to write:

```
await myClassInstance.myMethod(myParam).matchOk((x) => print(x));
await myClassInstance.myMethod(myParam).unwrapOrNull().then((x) => print(x));
print(myClassInstance.myMethod(myParam).unwrapOrNull());
```

Here is the code I have written:

```

import 'package:oxidized/oxidized.dart';

extension ResultOkMatcher<T extends Object, E extends Object> on Result<T, E> {
  /// Invokes the `okop` if the result is `Ok`, otherwise does nothing.
  void matchOk(void Function(T) okop) {
    if (this is Ok<T, E>) {
      okop((this as Ok<T, E>).value);
    }
  }

  /// Invokes the `errop` if the result is `Err`, otherwise does nothing.
  void matchErr(void Function(E) errop) {
    if (this is Err<T, E>) {
      errop((this as Err<T, E>).error);
    }
  }

  /// Unwraps a result, yielding the content of an `Ok`.
  ///
  /// If the value is an `Err`, returns `null` instead of throwing an exception.
  T? unwrapOrNull() {
    if (this is Ok<T, E>) {
      return (this as Ok<T, E>).value;
    } else {
      return null;
    }
  }
}

extension ResultFutureRedirector<T extends Object, E extends Object> on Future<Result<T, E>> {
  /// Invokes the `okop` if the result is `Ok`, otherwise does nothing.
  Future<void> matchOk(void Function(T) okop) async {
    final result = await this;
    if (result.isOk()) {
      okop(result.unwrap());
    }
  }

  /// Invokes the `errop` if the result is `Err`, otherwise does nothing.
  Future<void> matchErr(void Function(E) errop) async {
    final result = await this;
    if (result.isErr()) {
      errop(result.unwrapErr());
    }
  }

  /// Unwraps a result, yielding the content of an `Ok`.
  ///
  /// If the value is an `Err`, returns `null` instead of throwing an exception.
  Future<T?> unwrapOrNull() async {
    final result = await this;
    return result.isOk() ? result.unwrap() : null;
  }
}

```

These extensions provide methods such as matchOk, matchErr, unwrapOrNull (and maybe async versions?) which allow users to handle Ok and Err values without exceptions and in a more concise manner.

I believe that incorporating these methods into your library would greatly enhance its usability and align it with the patterns commonly used in Rust. Users familiar with Rust's Result type would find these methods intuitive and convenient.

Thank you for considering my request. I look forward to your feedback and the possibility of seeing these methods added to your library.

**Comment by nlfiedler** [comment]
I think that is splendid, please send a pull request. Thanks.

**Comment by JonasWanke** [comment]
Hi, I want to propose an alternative to `matchOk(…)` and `matchErr(…)`: If the `extends Object` bounds on the type parameters of `Result` were removed (as suggested previously: https://github.com/nlfiedler/oxidized/issues/10#issuecomment-1426223594), these two methods would be covered by `map(…)` and `mapErr(…)`, respectively. This doesn't work today because `void` or `null` aren't assignable to the non-null `Object`. On the other hand, `matchOk(…)` and `matchErr(…)` might have better semantics for this situation.

`result.unwrapOrNull()` sounds great! We used `result.ok().toNullable()` to achieve the same before, but it's more verbose and not as self-explanatory.

**Comment by amaxcz** [comment]
I'm not sure if the implementation I suggested is optimal or maximally efficient. It's more like a concept, and we should consider what else might be missing. The implementation using "final result = await this;" seems questionable to me.

Perhaps someone has better ideas on how to do it correctly?

**Comment by amaxcz** [comment]
@nlfiedler
I have made a pull request, please take a look. I attempted to implement it in a canonical "correct" style, following the author's approach.

https://github.com/nlfiedler/oxidized/pull/28
