### ISSUE TITLE
Discussion about some changes/additions

### ISSUE THREAD

**Issue by lemunozm** [nlfiedler/oxidized#7]
Hi again,

I am changing `dartz` to `oxidized` in my project, and in the process I have missed some minor functions that would improve the usage that I want to discuss:

- `isSome`, `isNone`, `isOk`, `isErr`: I saw in the changelog that you remove them to use the `is <Object>` dart check instead. Although this check works perfectly for all cases, it is very probable that during the life of a project you change `Option` by `Result` and vice-versa. When you do this kind of change, you want to be notified by the compiler of the places that you need to modify after this change. If I pass from `option is Some` to `result is Some` and I forgot to change `Some` by `Ok` it will still compile and I will introduce a potential bug in the application. Using the described functions will make the compiler notifying an error in these common situations and forces you to fix it.
- Keep the constructor parallelism in `Option` and `Result` after the null-safety change. If I write `Option::Some(...)` I expect that this option will be always a Some value. Currently, the signature can allow both, a value or a null to create a `Some` or a `None`, which can be confused. If I want this kind of behaviour It could be great to have a `Option.of(T? t)` (similar to the `Result.of`) that behaves in this way, and left `Option.Some` to receive a non-null value. 
  *EDIT: as `Result.of` receives a function instead of a value, maybe `Option.of` could be called `Option.from` to distinguish that behavior*

What do you think about it? 
If you agree, I can make the corresponding PRs.

Thanks!

**Comment by nlfiedler** [comment]
Yes, I agree. :) Thanks for the suggestions, and I look forward to your PR.
